# fly.toml app configuration file generated for ldm-archive-server-wandering-snowflake-8118 on 2025-06-14T15:58:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ldm-archive-server-wandering-snowflake-8118'
primary_region = 'atl'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
